name = "eng1300-mvp"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "eng1300-mvp"
database_id = "6b41a46e-d960-4e6d-8a2c-7e1816883f32"
